import { Hono } from 'hono'
import { afterEach,describe,expect,it,vi } from 'vitest'
import type { Env } from '../../src/env'
import { getWebSearchConfig,updateWebSearchConfig,resetWebSearchUsage,searchWeb } from '../../src/control/web-search'
import { emulateWebSearch } from '../../src/gateway/web-search'
import { applyMigrations,createSqliteD1 } from '../helpers/sqlite-d1'
function fixture(){const sqlite=createSqliteD1();applyMigrations(sqlite.raw);const env={DB:sqlite.d1,CREDENTIALS_MASTER_KEY:'m'.repeat(32)} as Env;const app=new Hono<{Bindings:Env}>();app.get('/settings',getWebSearchConfig);app.put('/settings',updateWebSearchConfig);app.post('/reset',resetWebSearchUsage);return {...sqlite,env,app}}
const provider={type:'tavily',api_key:'private-search-key',quota_limit:1,subscribed_at:null,expires_at:null,proxy_id:null}
async function configure(test:ReturnType<typeof fixture>,providers:unknown[]=[provider]){const response=await test.app.request('/settings',{method:'PUT',headers:{'content-type':'application/json','if-match':'"0"'},body:JSON.stringify({enabled:true,providers})},test.env);expect(response.status).toBe(200);return response.json()}
afterEach(()=>vi.unstubAllGlobals())
describe('persisted web search settings and actual consumers',()=>{
 it('stores encrypted keys, masks reads and preserves blank keys on update',async()=>{const t=fixture();try{expect(JSON.stringify(await configure(t))).not.toContain(provider.api_key);expect(JSON.stringify(t.raw.prepare('SELECT * FROM web_search_settings').get())).not.toContain(provider.api_key);const response=await t.app.request('/settings',{method:'PUT',headers:{'content-type':'application/json','if-match':'"1"'},body:JSON.stringify({enabled:true,providers:[{...provider,api_key:''}]})},t.env);expect(await response.json()).toMatchObject({data:{providers:[{api_key_configured:true}],control_version:2}})}finally{t.raw.close()}})
 it('enforces quota atomically across concurrent calls and supports reset',async()=>{const t=fixture();try{await configure(t);const fetcher=vi.fn(async(_url:unknown,_init?:RequestInit)=>Response.json({results:[{url:'https://example.com',title:'Title',content:'Result'}]}));vi.stubGlobal('fetch',fetcher);const results=await Promise.allSettled([searchWeb(t.env,'query'),searchWeb(t.env,'query')]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(fetcher).toHaveBeenCalledTimes(1);expect(JSON.parse(fetcher.mock.calls[0]?.[1]?.body as string)).toMatchObject({api_key:provider.api_key,query:'query'});const reset=await t.app.request('/reset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider_type:'tavily'})},t.env);expect(reset.status).toBe(200);await expect(searchWeb(t.env,'again')).resolves.toMatchObject({provider:'tavily'})}finally{t.raw.close()}})
 it('falls back after provider errors without exposing response secrets',async()=>{const t=fixture();try{await configure(t,[{...provider,type:'brave'},provider]);vi.stubGlobal('fetch',vi.fn(async(url:unknown)=>String(url).includes('brave')?new Response('private-search-key',{status:401}):Response.json({results:[]})));await expect(searchWeb(t.env,'query')).resolves.toMatchObject({provider:'tavily',results:[]})}finally{t.raw.close()}})
 it('consumes account policy for native stream and nonstream search with zero fabricated model tokens',async()=>{const t=fixture();try{await configure(t,[{...provider,quota_limit:null}]);t.raw.exec(`INSERT INTO accounts(id,name,platform,credential_ref,created_at_ms,updated_at_ms,protocol,base_url,auth_scheme,ui_config_json) VALUES('search-account','Search','anthropic','fixture',1,1,'anthropic','https://api.anthropic.com','x-api-key','{"extra":{"web_search_emulation":"enabled"}}')`);vi.stubGlobal('fetch',vi.fn(async()=>Response.json({results:[{url:'https://example.com',title:'Result',content:'Body'}]})));const body={model:'claude-test',tools:[{type:'web_search_20250305',name:'web_search'}],messages:[{role:'user',content:'test query'}]};const response=await emulateWebSearch(t.env,'search-account','group','anthropic',body,new AbortController().signal);expect(await response?.json()).toMatchObject({content:[{type:'server_tool_use'},{type:'web_search_tool_result'},{type:'text'}],usage:{input_tokens:0,output_tokens:0}});const stream=await emulateWebSearch(t.env,'search-account','group','anthropic',{...body,stream:true},new AbortController().signal);expect(await stream?.text()).toContain('event: message_stop');t.raw.exec(`UPDATE accounts SET ui_config_json='{"extra":{"web_search_emulation":"disabled"}}'`);expect(await emulateWebSearch(t.env,'search-account','group','anthropic',body,new AbortController().signal)).toBeNull()}finally{t.raw.close()}})
})
