PRAGMA foreign_keys = ON;

ALTER TABLE "groups" ADD COLUMN allow_image_generation INTEGER NOT NULL DEFAULT 0
  CHECK (allow_image_generation IN (0, 1));
ALTER TABLE "groups" ADD COLUMN allow_batch_image_generation INTEGER NOT NULL DEFAULT 0
  CHECK (allow_batch_image_generation IN (0, 1));
ALTER TABLE "groups" ADD COLUMN image_rate_independent INTEGER NOT NULL DEFAULT 0
  CHECK (image_rate_independent IN (0, 1));
ALTER TABLE "groups" ADD COLUMN image_rate_multiplier_ppm INTEGER NOT NULL DEFAULT 1000000
  CHECK (image_rate_multiplier_ppm BETWEEN 0 AND 10000000);
ALTER TABLE "groups" ADD COLUMN batch_image_discount_multiplier_ppm INTEGER NOT NULL DEFAULT 500000
  CHECK (batch_image_discount_multiplier_ppm BETWEEN 0 AND 10000000);
ALTER TABLE "groups" ADD COLUMN batch_image_hold_multiplier_ppm INTEGER NOT NULL DEFAULT 600000
  CHECK (
    batch_image_hold_multiplier_ppm BETWEEN 0 AND 10000000
    AND batch_image_hold_multiplier_ppm >= batch_image_discount_multiplier_ppm
  );
ALTER TABLE "groups" ADD COLUMN image_price_1k_micros INTEGER
  CHECK (image_price_1k_micros IS NULL OR image_price_1k_micros >= 0);
ALTER TABLE "groups" ADD COLUMN image_price_2k_micros INTEGER
  CHECK (image_price_2k_micros IS NULL OR image_price_2k_micros >= 0);
ALTER TABLE "groups" ADD COLUMN image_price_4k_micros INTEGER
  CHECK (image_price_4k_micros IS NULL OR image_price_4k_micros >= 0);

-- D1 is the source of truth. Large manifests and generated bytes are kept in
-- R2 and are reachable only through server-generated object keys.
CREATE TABLE media_tasks (
  id TEXT PRIMARY KEY CHECK (length(id) BETWEEN 32 AND 64),
  user_id TEXT NOT NULL REFERENCES users(id),
  api_key_id TEXT NOT NULL REFERENCES api_keys(id),
  group_id TEXT NOT NULL REFERENCES "groups"(id),
  parent_task_id TEXT REFERENCES media_tasks(id) ON DELETE RESTRICT,
  task_name TEXT NOT NULL DEFAULT '' CHECK (length(task_name) <= 255),
  provider TEXT NOT NULL CHECK (provider IN ('gemini_api')),
  model TEXT NOT NULL CHECK (length(model) BETWEEN 1 AND 200),
  upstream_model TEXT NOT NULL CHECK (length(upstream_model) BETWEEN 1 AND 200),
  image_size TEXT NOT NULL CHECK (image_size IN ('1K', '2K', '4K')),
  response_mime_type TEXT NOT NULL
    CHECK (response_mime_type IN ('image/png', 'image/jpeg', 'image/webp')),
  aspect_ratio TEXT CHECK (aspect_ratio IS NULL OR length(aspect_ratio) <= 32),
  status TEXT NOT NULL CHECK (status IN (
    'created', 'queued', 'running', 'settling', 'completed', 'failed',
    'cancelled', 'output_deleted'
  )),
  item_count INTEGER NOT NULL CHECK (item_count BETWEEN 1 AND 200),
  expected_output_count INTEGER NOT NULL CHECK (expected_output_count BETWEEN 1 AND 200),
  success_count INTEGER NOT NULL DEFAULT 0 CHECK (success_count BETWEEN 0 AND 200),
  fail_count INTEGER NOT NULL DEFAULT 0 CHECK (fail_count BETWEEN 0 AND 200),
  cancelled_count INTEGER NOT NULL DEFAULT 0 CHECK (cancelled_count BETWEEN 0 AND 200),
  base_unit_price_micros INTEGER NOT NULL CHECK (base_unit_price_micros >= 0),
  price_id TEXT NOT NULL REFERENCES model_prices(id),
  effective_rate_multiplier_ppm INTEGER NOT NULL CHECK (effective_rate_multiplier_ppm >= 0),
  batch_discount_multiplier_ppm INTEGER NOT NULL CHECK (batch_discount_multiplier_ppm >= 0),
  hold_multiplier_ppm INTEGER NOT NULL CHECK (hold_multiplier_ppm >= 0),
  billable_unit_price_micros INTEGER NOT NULL CHECK (billable_unit_price_micros >= 0),
  hold_unit_price_micros INTEGER NOT NULL CHECK (hold_unit_price_micros >= 0),
  estimated_cost_micros INTEGER NOT NULL CHECK (estimated_cost_micros >= 0),
  hold_amount_micros INTEGER NOT NULL CHECK (hold_amount_micros >= estimated_cost_micros),
  actual_cost_micros INTEGER CHECK (actual_cost_micros IS NULL OR actual_cost_micros >= 0),
  billing_type TEXT NOT NULL CHECK (billing_type IN ('balance', 'subscription')),
  subscription_id TEXT,
  platform_quota_platform TEXT,
  billing_status TEXT NOT NULL DEFAULT 'unreserved'
    CHECK (billing_status IN ('unreserved', 'reserved', 'settling', 'settled', 'released')),
  idempotency_key_hash TEXT NOT NULL CHECK (length(idempotency_key_hash) = 64),
  request_hash TEXT NOT NULL CHECK (length(request_hash) = 64),
  input_object_key TEXT NOT NULL UNIQUE CHECK (length(input_object_key) BETWEEN 16 AND 512),
  enqueued_at_ms INTEGER,
  provider_account_id TEXT,
  last_error_code TEXT CHECK (last_error_code IS NULL OR length(last_error_code) <= 128),
  last_error_message TEXT CHECK (last_error_message IS NULL OR length(last_error_message) <= 1000),
  version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  submitted_at_ms INTEGER,
  started_at_ms INTEGER,
  finished_at_ms INTEGER,
  settled_at_ms INTEGER,
  downloaded_at_ms INTEGER,
  output_deleted_at_ms INTEGER,
  user_deleted_at_ms INTEGER,
  UNIQUE (api_key_id, idempotency_key_hash),
  CHECK (
    (billing_type = 'balance' AND subscription_id IS NULL)
    OR (billing_type = 'subscription' AND subscription_id IS NOT NULL)
  )
) STRICT;

CREATE INDEX idx_media_tasks_owner_seek
  ON media_tasks(user_id, api_key_id, created_at_ms DESC, id DESC)
  WHERE user_deleted_at_ms IS NULL;
CREATE INDEX idx_media_tasks_queue
  ON media_tasks(status, enqueued_at_ms, created_at_ms, id)
  WHERE status IN ('created', 'queued', 'running', 'settling', 'cancelled');
CREATE INDEX idx_media_tasks_parent
  ON media_tasks(parent_task_id, created_at_ms DESC, id DESC)
  WHERE parent_task_id IS NOT NULL;

CREATE TRIGGER enforce_media_task_parent_owner_insert
BEFORE INSERT ON media_tasks
WHEN NEW.parent_task_id IS NOT NULL AND NOT EXISTS (
  SELECT 1 FROM media_tasks AS parent
   WHERE parent.id = NEW.parent_task_id
     AND parent.user_id = NEW.user_id
     AND parent.api_key_id = NEW.api_key_id
)
BEGIN
  SELECT RAISE(ABORT, 'media_task_parent_owner_mismatch');
END;

CREATE TABLE media_task_items (
  task_id TEXT NOT NULL REFERENCES media_tasks(id) ON DELETE CASCADE,
  custom_id TEXT NOT NULL CHECK (length(custom_id) BETWEEN 1 AND 255),
  ordinal INTEGER NOT NULL CHECK (ordinal BETWEEN 0 AND 199),
  status TEXT NOT NULL CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  output_count INTEGER NOT NULL CHECK (output_count BETWEEN 1 AND 4),
  image_count INTEGER NOT NULL DEFAULT 0 CHECK (image_count BETWEEN 0 AND 4),
  prompt_preview TEXT CHECK (prompt_preview IS NULL OR length(prompt_preview) <= 500),
  request_hash TEXT NOT NULL CHECK (length(request_hash) = 64),
  mime_type TEXT,
  file_extension TEXT,
  error_code TEXT CHECK (error_code IS NULL OR length(error_code) <= 128),
  error_message TEXT CHECK (error_message IS NULL OR length(error_message) <= 1000),
  attempt_token TEXT CHECK (attempt_token IS NULL OR length(attempt_token) BETWEEN 16 AND 64),
  attempt_started_at_ms INTEGER,
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 1000),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  completed_at_ms INTEGER,
  PRIMARY KEY (task_id, custom_id),
  UNIQUE (task_id, ordinal)
) STRICT;

CREATE INDEX idx_media_task_items_status
  ON media_task_items(task_id, status, ordinal, custom_id);
CREATE INDEX idx_media_task_items_lease
  ON media_task_items(task_id, status, attempt_started_at_ms, ordinal);

CREATE TABLE media_task_outputs (
  task_id TEXT NOT NULL,
  custom_id TEXT NOT NULL,
  image_index INTEGER NOT NULL CHECK (image_index BETWEEN 0 AND 3),
  object_key TEXT NOT NULL UNIQUE CHECK (length(object_key) BETWEEN 16 AND 512),
  mime_type TEXT NOT NULL CHECK (mime_type IN ('image/png', 'image/jpeg', 'image/webp')),
  file_extension TEXT NOT NULL CHECK (file_extension IN ('png', 'jpg', 'webp')),
  byte_length INTEGER NOT NULL CHECK (byte_length BETWEEN 1 AND 33554432),
  sha256 TEXT NOT NULL CHECK (length(sha256) = 64),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (task_id, custom_id, image_index),
  FOREIGN KEY (task_id, custom_id)
    REFERENCES media_task_items(task_id, custom_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE media_task_events (
  id TEXT PRIMARY KEY CHECK (length(id) BETWEEN 32 AND 64),
  task_id TEXT NOT NULL REFERENCES media_tasks(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (length(event_type) BETWEEN 1 AND 64),
  payload_json TEXT NOT NULL DEFAULT '{}'
    CHECK (json_valid(payload_json) AND json_type(payload_json) = 'object'),
  event_hash TEXT NOT NULL CHECK (length(event_hash) = 64),
  occurred_at_ms INTEGER NOT NULL CHECK (occurred_at_ms >= 0),
  UNIQUE (task_id, event_hash)
) STRICT;

CREATE INDEX idx_media_task_events_seek
  ON media_task_events(task_id, occurred_at_ms, id);

CREATE TRIGGER prevent_media_task_events_update
BEFORE UPDATE ON media_task_events
BEGIN
  SELECT RAISE(ABORT, 'media_task_event_immutable');
END;

CREATE TRIGGER prevent_media_task_events_delete
BEFORE DELETE ON media_task_events
WHEN EXISTS (SELECT 1 FROM media_tasks WHERE id = OLD.task_id)
BEGIN
  SELECT RAISE(ABORT, 'media_task_event_immutable');
END;

INSERT INTO schema_migrations(version, name, applied_at_ms)
VALUES (43, 'media_tasks', CAST(unixepoch('subsec') * 1000 AS INTEGER));
