import type { Context } from 'hono'
import type { Env } from '../env'
import { asGatewayError, GatewayError } from '../gateway/errors'
import { authenticateAdminSession } from './admin-auth'
import { controlIdempotency, controlIdempotencyInsert, findControlIdempotency, parseIdempotentResponse } from './idempotency'
import { controlError, controlSuccess, requireExpectedControlVersion, requireIdempotencyKey, requireResourceId, readJsonObject } from './http'

type Bindings = { Bindings: Env }
type AttributeType = 'text' | 'textarea' | 'number' | 'email' | 'url' | 'date' | 'select' | 'multi_select'
const TYPES: AttributeType[] = ['text', 'textarea', 'number', 'email', 'url', 'date', 'select', 'multi_select']
const MAX_BATCH = 100
const MAX_VALUES = 100
interface DefinitionRow { id:number; key:string; name:string; description:string|null; type:AttributeType; options_json:string; required:number; validation_json:string; placeholder:string|null; display_order:number; enabled:number; control_version:number; created_at_ms:number; updated_at_ms:number }
interface ValueRow { id:number; user_id:string; attribute_id:number; value:string; control_version:number; created_at_ms:number; updated_at_ms:number }
interface Input { key:string; name:string; description:string|null; type:AttributeType; options: Array<{ value:string; label:string }>; required:boolean; validation:Record<string, unknown>; placeholder:string|null; enabled:boolean; display_order?:number }

export async function listUserAttributeDefinitions(c: Context<Bindings>): Promise<Response> { try {
  const enabled = c.req.query('enabled')
  if (enabled !== undefined && enabled !== 'true' && enabled !== 'false') throw new GatewayError(400, 'invalid_enabled', 'enabled must be true or false')
  const rows = await c.env.DB.prepare(`SELECT ${DEF_COLUMNS} FROM user_attribute_definitions WHERE deleted_at_ms IS NULL${enabled === undefined ? '' : ' AND enabled = ?'} ORDER BY display_order, id`).bind(...(enabled === undefined ? [] : [enabled === 'true' ? 1 : 0])).all<DefinitionRow>()
  return controlSuccess(rows.results.map(publicDefinition))
} catch (e) { return controlError(asGatewayError(e)) } }

export async function createUserAttributeDefinition(c: Context<Bindings>): Promise<Response> { try {
  const actor = await authenticateAdminSession(c.req.raw, c.env); const key = requireIdempotencyKey(c.req.raw); const input = parseInput(await readJsonObject(c.req.raw), true)
  const idem = await controlIdempotency('admin.user-attributes.create.v1', key, input); const replay = await findControlIdempotency(c.env, idem); if (replay) return controlSuccess(parseIdempotentResponse(replay, 'user_attribute_definition'))
  const now = Date.now(); const order = input.display_order ?? await nextOrder(c.env)
  await c.env.DB.prepare(`INSERT INTO user_attribute_definitions (key,name,description,type,options_json,required,validation_json,placeholder,display_order,enabled,created_at_ms,updated_at_ms) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(input.key,input.name,input.description,input.type,JSON.stringify(input.options),input.required ? 1 : 0,JSON.stringify(input.validation),input.placeholder,order,input.enabled ? 1 : 0,now,now).run()
  const row = await c.env.DB.prepare(`SELECT ${DEF_COLUMNS} FROM user_attribute_definitions WHERE key = ? AND deleted_at_ms IS NULL`).bind(input.key).first<DefinitionRow>()
  if (row === null) throw new GatewayError(503, 'attribute_create_failed', 'attribute definition was not persisted', 'server_error')
  const response = publicDefinition(row)
  await c.env.DB.batch([controlIdempotencyInsert(c.env, idem, 'user_attribute_definition', String(row.id), response, now), audit(c.env, actor.user_id, 'definition.create', 'definition', String(row.id), row.control_version, now)])
  return controlSuccess(response, 201)
} catch (e) { return controlError(mapWriteError(e)) } }

export async function updateUserAttributeDefinition(c: Context<Bindings>): Promise<Response> { try {
  const actor = await authenticateAdminSession(c.req.raw, c.env); const id = numericId(c.req.param('id'), 'attribute'); const key = requireIdempotencyKey(c.req.raw); const body = await readJsonObject(c.req.raw); const expected = requireExpectedControlVersion(c.req.raw, body); const current = await requireDefinition(c.env,id); const input = parseInput({ ...publicDefinition(current), ...body }, true)
  if (current.control_version !== expected) throw conflict()
  const idem = await controlIdempotency('admin.user-attributes.update.v1', key, {id,expected,input}); const replay = await findControlIdempotency(c.env, idem); if (replay) return controlSuccess(parseIdempotentResponse(replay, 'user_attribute_definition'))
  const now=Date.now(); const update = await c.env.DB.prepare(`UPDATE user_attribute_definitions SET key=?,name=?,description=?,type=?,options_json=?,required=?,validation_json=?,placeholder=?,display_order=?,enabled=?,control_version=control_version+1,updated_at_ms=? WHERE id=? AND deleted_at_ms IS NULL AND control_version=?`).bind(input.key,input.name,input.description,input.type,JSON.stringify(input.options),input.required?1:0,JSON.stringify(input.validation),input.placeholder,input.display_order ?? current.display_order,input.enabled?1:0,now,id,expected).run(); if (update.meta.changes !== 1) throw conflict()
  const row=await requireDefinition(c.env,id); const response=publicDefinition(row); await c.env.DB.batch([controlIdempotencyInsert(c.env,idem,'user_attribute_definition',String(id),response,now),audit(c.env,actor.user_id,'definition.update','definition',String(id),row.control_version,now)]); return controlSuccess(response)
} catch(e) { return controlError(mapWriteError(e)) } }

export async function deleteUserAttributeDefinition(c: Context<Bindings>): Promise<Response> { try {
  const actor=await authenticateAdminSession(c.req.raw,c.env); const id=numericId(c.req.param('id'),'attribute'); const key=requireIdempotencyKey(c.req.raw); const body=await readJsonObject(c.req.raw,1024); const expected=requireExpectedControlVersion(c.req.raw,body); const current=await requireDefinition(c.env,id); if(current.control_version!==expected) throw conflict(); const idem=await controlIdempotency('admin.user-attributes.delete.v1',key,{id,expected}); const replay=await findControlIdempotency(c.env,idem); if(replay) return controlSuccess(parseIdempotentResponse(replay,'user_attribute_delete')); const now=Date.now(); const changed=await c.env.DB.prepare('UPDATE user_attribute_definitions SET deleted_at_ms=?, enabled=0, control_version=control_version+1, updated_at_ms=? WHERE id=? AND deleted_at_ms IS NULL AND control_version=?').bind(now,now,id,expected).run(); if(changed.meta.changes!==1) throw conflict(); const response={message:'attribute definition deleted'}; await c.env.DB.batch([controlIdempotencyInsert(c.env,idem,'user_attribute_delete',String(id),response,now),audit(c.env,actor.user_id,'definition.delete','definition',String(id),expected+1,now)]); return controlSuccess(response)
} catch(e) { return controlError(mapWriteError(e)) } }

export async function reorderUserAttributeDefinitions(c: Context<Bindings>): Promise<Response> { try {
  const actor=await authenticateAdminSession(c.req.raw,c.env); const key=requireIdempotencyKey(c.req.raw); const body=await readJsonObject(c.req.raw,16384); const expected=requireExpectedControlVersion(c.req.raw,body); const ids=parseIds(body.ids,MAX_VALUES); const config=await c.env.DB.prepare('SELECT control_version FROM user_attribute_configuration WHERE singleton=1').first<{control_version:number}>(); if(!config || config.control_version!==expected) throw conflict(); const live=await c.env.DB.prepare('SELECT id FROM user_attribute_definitions WHERE deleted_at_ms IS NULL ORDER BY id').all<{id:number}>(); if(ids.length!==live.results.length || new Set(ids).size!==ids.length || ids.some(id=>!live.results.some(x=>x.id===id))) throw new GatewayError(400,'invalid_reorder','ids must contain every live attribute exactly once'); const idem=await controlIdempotency('admin.user-attributes.reorder.v1',key,{ids,expected}); const replay=await findControlIdempotency(c.env,idem); if(replay)return controlSuccess(parseIdempotentResponse(replay,'user_attribute_reorder')); const now=Date.now(); const statements=ids.map((id,index)=>c.env.DB.prepare('UPDATE user_attribute_definitions SET display_order=?,updated_at_ms=? WHERE id=?').bind(index,now,id)); statements.push(c.env.DB.prepare('UPDATE user_attribute_configuration SET control_version=control_version+1,updated_at_ms=? WHERE singleton=1 AND control_version=?').bind(now,expected)); const response={message:'attribute definitions reordered',control_version:expected+1}; statements.push(controlIdempotencyInsert(c.env,idem,'user_attribute_reorder','configuration',response,now),audit(c.env,actor.user_id,'definition.reorder','configuration','singleton',expected+1,now)); const r=await c.env.DB.batch(statements); if(r[ids.length].meta.changes!==1) throw conflict(); return controlSuccess(response)
} catch(e){return controlError(mapWriteError(e))} }

export async function getAdminUserAttributes(c: Context<Bindings>): Promise<Response> { try { const userId=requireResourceId(c.req.param('id'),'user'); await requireUser(c.env,userId); const rows=await c.env.DB.prepare(`SELECT v.id,v.user_id,v.attribute_id,v.value,v.control_version,v.created_at_ms,v.updated_at_ms FROM user_attribute_values v JOIN user_attribute_definitions d ON d.id=v.attribute_id WHERE v.user_id=? AND d.deleted_at_ms IS NULL ORDER BY d.display_order,d.id`).bind(userId).all<ValueRow>(); return controlSuccess(rows.results.map(publicValue)) }catch(e){return controlError(asGatewayError(e))} }

export async function updateAdminUserAttributes(c: Context<Bindings>): Promise<Response> { try { const actor=await authenticateAdminSession(c.req.raw,c.env); const userId=requireResourceId(c.req.param('id'),'user'); const user=await requireUser(c.env,userId); const key=requireIdempotencyKey(c.req.raw); const body=await readJsonObject(c.req.raw,128*1024); const expected=requireExpectedControlVersion(c.req.raw,body); if(user.control_version!==expected)throw conflict(); const values=parseValues(body.values); const defs=await c.env.DB.prepare(`SELECT ${DEF_COLUMNS} FROM user_attribute_definitions WHERE deleted_at_ms IS NULL AND enabled=1`).all<DefinitionRow>(); const byId=new Map(defs.results.map(x=>[x.id,x])); for(const [id,value] of Object.entries(values)){const def=byId.get(Number(id));if(!def)throw new GatewayError(400,'attribute_not_found','attribute definition is not enabled'); validateValue(def,value)} const idem=await controlIdempotency('admin.users.attributes.put.v1',key,{userId,expected,values});const replay=await findControlIdempotency(c.env,idem);if(replay)return controlSuccess(parseIdempotentResponse(replay,'user_attribute_values')); const now=Date.now(); const claimed=await c.env.DB.prepare('UPDATE users SET control_version=control_version+1,updated_at_ms=? WHERE id=? AND control_version=? RETURNING control_version').bind(now,userId,expected).first<{control_version:number}>(); if(claimed===null)throw conflict(); const stmts:D1PreparedStatement[]=[]; for(const [id,value] of Object.entries(values)){if(value==='')stmts.push(c.env.DB.prepare('DELETE FROM user_attribute_values WHERE user_id=? AND attribute_id=?').bind(userId,Number(id)));else stmts.push(c.env.DB.prepare('INSERT INTO user_attribute_values (user_id,attribute_id,value,created_at_ms,updated_at_ms) VALUES (?,?,?,?,?) ON CONFLICT(user_id,attribute_id) DO UPDATE SET value=excluded.value,control_version=user_attribute_values.control_version+1,updated_at_ms=excluded.updated_at_ms').bind(userId,Number(id),value,now,now))}; const response={message:'user attributes updated',control_version:claimed.control_version}; stmts.push(controlIdempotencyInsert(c.env,idem,'user_attribute_values',userId,response,now),audit(c.env,actor.user_id,'values.update','user',userId,claimed.control_version,now)); await c.env.DB.batch(stmts); return controlSuccess(response) }catch(e){return controlError(mapWriteError(e))} }

export async function batchGetAdminUserAttributes(c: Context<Bindings>): Promise<Response> { try { const body=await readJsonObject(c.req.raw,16*1024); const ids=parseUserIds(body.user_ids); if(ids.length===0)return controlSuccess({attributes:{}}); const marks=ids.map(()=>'?').join(','); const rows=await c.env.DB.prepare(`SELECT v.user_id,v.attribute_id,v.value FROM user_attribute_values v JOIN user_attribute_definitions d ON d.id=v.attribute_id WHERE v.user_id IN (${marks}) AND d.deleted_at_ms IS NULL`).bind(...ids).all<{user_id:string;attribute_id:number;value:string}>(); const attributes:Record<string,Record<string,string>>={}; for(const row of rows.results)(attributes[row.user_id]??={})[String(row.attribute_id)]=row.value; return controlSuccess({attributes}) }catch(e){return controlError(asGatewayError(e))} }

const DEF_COLUMNS='id,key,name,description,type,options_json,required,validation_json,placeholder,display_order,enabled,control_version,created_at_ms,updated_at_ms'
async function requireDefinition(env:Env,id:number){const row=await env.DB.prepare(`SELECT ${DEF_COLUMNS} FROM user_attribute_definitions WHERE id=? AND deleted_at_ms IS NULL`).bind(id).first<DefinitionRow>();if(!row)throw new GatewayError(404,'attribute_not_found','attribute definition not found');return row}
async function requireUser(env:Env,id:string){const row=await env.DB.prepare('SELECT control_version FROM users WHERE id=?').bind(id).first<{control_version:number}>();if(!row)throw new GatewayError(404,'user_not_found','user not found');return row}
async function nextOrder(env:Env){const row=await env.DB.prepare('SELECT COALESCE(MAX(display_order),-1)+1 AS value FROM user_attribute_definitions WHERE deleted_at_ms IS NULL').first<{value:number}>();return row?.value??0}
function publicDefinition(r:DefinitionRow){return {id:r.id,key:r.key,name:r.name,description:r.description,type:r.type,options:JSON.parse(r.options_json),required:r.required===1,validation:JSON.parse(r.validation_json),placeholder:r.placeholder,display_order:r.display_order,enabled:r.enabled===1,control_version:r.control_version,created_at:new Date(r.created_at_ms).toISOString(),updated_at:new Date(r.updated_at_ms).toISOString()}}
function publicValue(r:ValueRow){return {id:r.id,user_id:r.user_id,attribute_id:r.attribute_id,value:r.value,control_version:r.control_version,created_at:new Date(r.created_at_ms).toISOString(),updated_at:new Date(r.updated_at_ms).toISOString()}}
function parseInput(v:Record<string,unknown>,required:boolean):Input{const string=(name:string,max:number,nullable=false)=>{const x=v[name];if(nullable&&(x===undefined||x===null||x===''))return null;if(typeof x!=='string'||x.trim()===''||x.length>max)throw new GatewayError(400,`invalid_${name}`,`${name} is invalid`);return x.trim()};const key=string('key',64) as string;const name=string('name',128) as string;const type=v.type;if(!TYPES.includes(type as AttributeType))throw new GatewayError(400,'invalid_type','attribute type is invalid');const options=parseOptions(v.options);if((type==='select'||type==='multi_select')&&options.length===0)throw new GatewayError(400,'invalid_options','select attributes require options');const validation=parseValidation(v.validation);const display=v.display_order===undefined?undefined:positiveInt(v.display_order,'display_order');return {key,name,description:string('description',1024,true),type:type as AttributeType,options,required:bool(v.required,'required',false),validation,placeholder:string('placeholder',256,true),enabled:bool(v.enabled,'enabled',true),display_order:display}}
function parseOptions(v:unknown){if(v===undefined)return [];if(!Array.isArray(v)||v.length>100)throw new GatewayError(400,'invalid_options','options is invalid');const used=new Set<string>();return v.map(x=>{if(!x||typeof x!=='object'||typeof (x as any).value!=='string'||typeof (x as any).label!=='string'||!(x as any).value.trim()||(x as any).value.length>128||(x as any).label.length>256)throw new GatewayError(400,'invalid_options','options is invalid');const value=(x as any).value.trim();if(used.has(value))throw new GatewayError(400,'invalid_options','option values must be unique');used.add(value);return {value,label:(x as any).label.trim()}})}
function parseValidation(v:unknown){if(v===undefined)return {};if(!v||typeof v!=='object'||Array.isArray(v))throw new GatewayError(400,'invalid_validation','validation is invalid');const out:Record<string,unknown>={};for(const k of ['min_length','max_length','min','max'])if((v as any)[k]!==undefined){if(!Number.isFinite((v as any)[k]))throw new GatewayError(400,'invalid_validation','validation is invalid');out[k]=(v as any)[k]}if(typeof (v as any).pattern==='string'){if((v as any).pattern.length>256)throw new GatewayError(400,'invalid_validation','validation is invalid');try{new RegExp((v as any).pattern)}catch{throw new GatewayError(400,'invalid_validation','validation pattern is invalid')}out.pattern=(v as any).pattern}return out}
function bool(v:unknown,n:string,f:boolean){if(v===undefined)return f;if(typeof v!=='boolean')throw new GatewayError(400,`invalid_${n}`,`${n} is invalid`);return v}
function positiveInt(v:unknown,n:string){if(!Number.isSafeInteger(v)||Number(v)<0||Number(v)>1_000_000)throw new GatewayError(400,`invalid_${n}`,`${n} is invalid`);return Number(v)}
function numericId(v:string|undefined,n:string){if(!v||!/^\d+$/.test(v)||!Number.isSafeInteger(Number(v))||Number(v)<1)throw new GatewayError(400,`invalid_${n}_id`,`${n} id is invalid`);return Number(v)}
function parseIds(v:unknown,max:number){if(!Array.isArray(v)||v.length>max)return (()=>{throw new GatewayError(400,'invalid_ids','ids is invalid')})();return v.map(x=>positiveInt(x,'id'))}
function parseUserIds(v:unknown){if(!Array.isArray(v)||v.length>MAX_BATCH)throw new GatewayError(400,'invalid_user_ids','user_ids must contain at most 100 ids');const ids=v.map(x=>{if(typeof x!=='string'||x.length===0||x.length>128||/[\u0000-\u001f]/.test(x))throw new GatewayError(400,'invalid_user_ids','user_ids must be Worker user ids');return x});if(new Set(ids).size!==ids.length)throw new GatewayError(400,'invalid_user_ids','user_ids must be unique');return ids}
function parseValues(v:unknown){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length>MAX_VALUES)throw new GatewayError(400,'invalid_values','values is invalid');const result:Record<string,string>={};for(const [id,value] of Object.entries(v)){numericId(id,'attribute');if(typeof value!=='string'||value.length>16384)throw new GatewayError(400,'invalid_value','attribute value is invalid');result[id]=value}return result}
function validateValue(def:DefinitionRow,value:string){const val=JSON.parse(def.validation_json) as any;if(value===''&&def.required===1)throw new GatewayError(400,'attribute_required',`${def.name} is required`);if(value==='' )return;if(val.min_length!==undefined&&value.length<val.min_length||val.max_length!==undefined&&value.length>val.max_length)throw new GatewayError(400,'attribute_validation_failed','attribute length is invalid');if(def.type==='number'){const n=Number(value);if(!Number.isFinite(n)||(val.min!==undefined&&n<val.min)||(val.max!==undefined&&n>val.max))throw new GatewayError(400,'attribute_validation_failed','attribute number is invalid')}if(val.pattern&&!(new RegExp(val.pattern)).test(value))throw new GatewayError(400,'attribute_validation_failed','attribute value does not match pattern');const opts=new Set((JSON.parse(def.options_json) as Array<{value:string}>).map(x=>x.value));if(def.type==='select'&&!opts.has(value))throw new GatewayError(400,'attribute_validation_failed','attribute option is invalid');if(def.type==='multi_select'){let selected:string[];try{selected=JSON.parse(value)}catch{selected=value.split(',').map(x=>x.trim()).filter(Boolean)}if(!Array.isArray(selected)||selected.some(x=>typeof x!=='string'||!opts.has(x)))throw new GatewayError(400,'attribute_validation_failed','attribute options are invalid')}}
function conflict(){return new GatewayError(409,'control_version_conflict','resource has changed; reload and retry')}
function mapWriteError(e:unknown){if(e instanceof GatewayError)return e;const m=e instanceof Error?e.message:'';if(/UNIQUE constraint failed: user_attribute_definitions.key/i.test(m))return new GatewayError(409,'attribute_key_exists','attribute key already exists');return asGatewayError(e)}
function audit(env:Env,actor:string,action:string,type:string,id:string,version:number|null,now:number){return env.DB.prepare('INSERT INTO user_attribute_audit_events (id,actor_user_id,action,resource_type,resource_id,control_version,metadata_json,occurred_at_ms) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),actor,action,type,id,version,'{}',now)}
